### ISSUE TITLE
Rendering Bug found for Minecraft MC 1.12.2 

### ISSUE THREAD

**Issue by Titoo8899** [AHilyard/EquipmentCompare#11]
The Last new Mod was SnowTime Mod Version 1.0 and I think it give in this area a Problem then I look then the crash was. In the main menu is all good and only by the Singleplayer area of Worlds crash the game. I hope you can a Fix for Minecraft MC 1.12.2 in next time make.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Fluidlogged API Plugin (Fluidlogged-API-v1.8.1e-mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 10/17/22 7:05 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at com.anthonyhilyard.equipmentcompare.gui.ComparisonTooltips.render(ComparisonTooltips.java:142)
	at com.anthonyhilyard.equipmentcompare.gui.ComparisonTooltips.render(ComparisonTooltips.java:130)
	at net.minecraft.client.gui.GuiScreen.handler$zza000$renderTooltip(GuiScreen.java:791)
	at net.minecraft.client.gui.GuiScreen.drawHoveringText(GuiScreen.java)
	at net.minecraft.client.gui.GuiScreen.func_146283_a(GuiScreen.java:177)
	at net.minecraft.client.gui.GuiWorldSelection.func_73863_a(SourceFile:110)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.anthonyhilyard.equipmentcompare.gui.ComparisonTooltips.render(ComparisonTooltips.java:142)
	at com.anthonyhilyard.equipmentcompare.gui.ComparisonTooltips.render(ComparisonTooltips.java:130)
	at net.minecraft.client.gui.GuiScreen.handler$zza000$renderTooltip(GuiScreen.java:791)
	at net.minecraft.client.gui.GuiScreen.drawHoveringText(GuiScreen.java)
	at net.minecraft.client.gui.GuiScreen.func_146283_a(GuiScreen.java:177)
	at net.minecraft.client.gui.GuiWorldSelection.func_73863_a(SourceFile:110)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.GuiWorldSelection
	Mouse location: Scaled: (105, 134). Absolute: (421, 437)
	Screen size: Scaled: (480, 244). Absolute: (1920, 974). Scale factor of 4
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 322403768 bytes (307 MB) / 1073741824 bytes (1024 MB) up to 10737418240 bytes (10240 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 12 mods loaded, 12 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                | Version      | Source                               | Signature                                |
	|:------ |:----------------- |:------------ |:------------------------------------ |:---------------------------------------- |
	| LCHIJA | minecraft         | 1.12.2       | minecraft.jar                        | None                                     |
	| LCHIJA | mcp               | 9.42         | minecraft.jar                        | None                                     |
	| LCHIJA | FML               | 8.0.99.99    | forge-1.12.2-14.23.5.2860.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge             | 14.23.5.2860 | forge-1.12.2-14.23.5.2860.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | equipmentcompare  | 1.3.3        | EquipmentCompare-1.12.2-1.3.3.jar    | None                                     |
	| LCHIJA | firstaid          | 1.6.21       | firstaid-1.6.21.jar                  | 7904c4e13947c8a616c5f39b26bdeba796500722 |
	| LCHIJA | fluidlogged_api   | 1.8.1e       | Fluidlogged-API-v1.8.1e-mc1.12.2.jar | None                                     |
	| LCHIJA | legendarytooltips | 1.1.8        | LegendaryTooltips-1.12.2-1.1.8.jar   | None                                     |
	| LCHIJA | payday            | 3.0          | payday-3.2-1.12.2.jar                | None                                     |
	| LCHIJA | quickstore        | 1.4          | quickstore-1.5.jar                   | None                                     |
	| LCHIJA | snowtime          | 1.0-SNAPSHOT | snowtime-1.0-SNAPSHOT.jar            | None                                     |
	| LCHIJA | worlddefender     | 1.2.0        | worldDefender-1.2.0.jar              | None                                     |

	Loaded coremods (and transformers): 
Fluidlogged API Plugin (Fluidlogged-API-v1.8.1e-mc1.12.2.jar)
  git.jbredwards.fluidlogged_api.mod.asm.ASMHandler$Transformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 522.25' Renderer: 'NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2'
	Launched Version: 1.12.2-forge-14.23.5.2860
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 522.25, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz

**Comment by AHilyard** [comment]
This issue has been moved to discord: https://discord.gg/UCKjnamDaW
I am much more active there, and it should get more attention there.  Thank you for understanding.
