### ISSUE TITLE
1.3.8 don't work on Fabric 1.20.x

### ISSUE THREAD

**Issue by KIRUYXAN** [AHilyard/EquipmentCompare#35]
I have this error when I start Fabric 1.20:

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Inventory Tabs' (inventory-tabs) 1.1.8+1.20 with any version that is compatible with:
		 - minecraft 1.20
	 - Replace mod 'Forge Config API Port' (forgeconfigapiport) 7.0.0 with version 8.0 or later.
More details:
	 - Mod 'LibGui' (libgui) 8.1.0+1.20.1 requires version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20!
	 **- Mod 'Equipment Compare' (equipmentcompare) 1.3.8 requires version 8.0 or later of mod 'Forge Config API Port' (forgeconfigapiport), but only the wrong version is present: 7.0.0!**
	 - Mod 'Inventory Tabs' (inventory-tabs) 1.1.8+1.20 requires version 1.20.1 or later of 'Minecraft' (minecraft), but only the wrong version is present: 1.20!
	 - Mod 'Jankson' (jankson) 6.0.0+j1.2.3 requires version 1.20.1 or later of 'Minecraft' (minecraft), but only the wrong version is present: 1.20!
	 - Mod 'Tinfoiled Cotton Client Commands' (cotton-client-commands) 1.1.0+1.15.2 requires any version between 1.14- (inclusive) and 1.16- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.20!
	 - Mod 'ViaFabric for 1.14' (viafabric-mc114) 0.4.10+39-main requires any 1.14.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.20!
	 - Mod 'ViaFabric for 1.15' (viafabric-mc115) 0.4.10+39-main requires any 1.15.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.20!
	 - Mod 'ViaFabric for 1.16' (viafabric-mc116) 0.4.10+39-main requires any 1.16.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.20!
	 - Mod 'ViaFabric for 1.17' (viafabric-mc117) 0.4.10+39-main requires any 1.17.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.20!
	 - Mod 'ViaFabric for 1.18' (viafabric-mc118) 0.4.10+39-main requires any 1.18.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.20!
	 - Mod 'ViaFabric for 1.19' (viafabric-mc119) 0.4.10+39-main requires any 1.19.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.20!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

But the lastest version of Forge Config API Port is 7.0.0 and it isn't need for this mod:

![NVIDIA_Share_U6VjoY6rtY](https://github.com/AHilyard/EquipmentCompare/assets/65653126/b36d41d6-97e8-40e3-836d-cb2eec743434)
![NVIDIA_Share_7zYqswAeZd](https://github.com/AHilyard/EquipmentCompare/assets/65653126/b0a75f72-4a38-491e-b3cc-27718fa91874)

**Comment by AHilyard** [comment]
This issue has been moved to discord: https://discord.gg/UCKjnamDaW
I am much more active there, and it should get more attention there. Thank you for understanding.
