### ISSUE TITLE
Possible mod conflict with accessories? - Fabric 1.21

### ISSUE THREAD

**Issue by Hiusi** [AHilyard/EquipmentCompare#42]
console spams this error, I'm guessing that I use Accessories instead of trinkets?
Fabric 1.21
https://modrinth.com/mod/accessories
https://modrinth.com/mod/accessories-tc-layer

```
[08:31:43] [Render thread/ERROR]: java.lang.ClassNotFoundException: com.anthonyhilyard.equipmentcompare.compat.TrinketsHandler
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at java.base/java.lang.Class.forName(Unknown Source)
	at com.anthonyhilyard.equipmentcompare.gui.ComparisonTooltips.render(ComparisonTooltips.java:174)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.class_332.renderComparisonTooltips(class_332.java:6395)
	at net.minecraft.class_332.handler$dbp000$equipmentcompare$renderTooltipInternal(class_332.java:6441)
	at net.minecraft.class_332.method_51435(class_332.java)
	at net.minecraft.class_332.method_51437(class_332.java:651)
	at net.minecraft.class_465.method_2380(class_465.java:182)
	at moe.plushie.armourers_workshop.compatibility.client.gui.AbstractMenuScreenImpl.renderTooltip(AbstractMenuScreenImpl.java:39)
	at moe.plushie.armourers_workshop.core.client.gui.widget.ContainerMenuScreen._renderTooltip(ContainerMenuScreen.java:144)
	at com.apple.library.impl.WindowManagerImpl.render(WindowManagerImpl.java:104)
	at moe.plushie.armourers_workshop.core.client.gui.widget.ContainerMenuScreen.render(ContainerMenuScreen.java:67)
	at moe.plushie.armourers_workshop.compatibility.client.gui.AbstractMenuScreenImpl.method_25394(AbstractMenuScreenImpl.java:52)
	at net.minecraft.class_437.method_47413(class_437.java:117)
	at net.minecraft.class_757.mixinextras$bridge$method_47413$277(class_757.java)
	at net.minecraft.class_757.wrapOperation$dli000$fabric-screen-api-v1$onRenderScreen(class_757.java:5586)
	at net.minecraft.class_757.mixinextras$bridge$wrapOperation$dli000$fabric-screen-api-v1$onRenderScreen$278(class_757.java)
	at net.minecraft.class_757.wrapOperation$dpa000$fancymenu$wrapRenderScreenFancyMenu(class_757.java:6570)
	at net.minecraft.class_757.mixinextras$bridge$wrapOperation$dpa000$fancymenu$wrapRenderScreenFancyMenu$279(class_757.java)
	at net.minecraft.class_757.wrapOperation$fae000$konkrete$wrapRenderScreen_Konkrete(class_757.java:9102)
	at net.minecraft.class_757.method_3192(class_757.java:913)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by AHilyard** [comment]
Thank you for the report, I have added support for Accessories in the latest update. :)
