### ISSUE TITLE
[1.19.2] Error in Render Thread when comparing equipment

### ISSUE THREAD

**Issue by fabrego524** [AHilyard/EquipmentCompare#46]
Any time I use the equipment compare in the inventory, everything seems to render fine. However, the console gets spammed with an error caused by the LegendaryTooltopsConfig package. I'm using the only version available for 1.19.2

```
[01:48:56] [Render thread/ERROR]:java.lang.reflect.InvocationTargetException	
        at jdk.internal.reflect.GeneratedMethodAccessor38.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at knot//com.anthonyhilyard.equipmentcompare.gui.ComparisonTooltips.render(ComparisonTooltips.java:214)
	at knot//net.minecraft.class_437.handler$dhc000$equipmentcompare$renderTooltip(class_437.java:5761)
	at knot//net.minecraft.class_437.method_25409(class_437.java)
	at knot//net.minecraft.class_465.method_2380(class_465.java:189)
	at knot//net.minecraft.class_476.method_25394(class_476.java:32)
	at knot//net.minecraft.class_757.method_3192(class_757.java:881)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1177)
	at knot//net.minecraft.class_310.method_1514(class_310.java:768)
	at knot//net.minecraft.client.main.Main.method_44604(Main.java:244)
	at knot//net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: com/anthonyhilyard/legendarytooltips/LegendaryTooltipsConfig
	at knot//com.anthonyhilyard.equipmentcompare.compat.LegendaryTooltipsHandler.getCenteredTitle(LegendaryTooltipsHandler.java:9)
	... 16 more
Caused by: java.lang.ClassNotFoundException: com.anthonyhilyard.legendarytooltips.LegendaryTooltipsConfig
	... 17 more
```

**Comment by AHilyard** [comment]
This issue has been moved to discord: https://discord.gg/UCKjnamDaW
I am much more active there, and it should get more attention there. Thank you for understanding.
